version: '3.6'

services:
  bddmysql:
    container_name: "jee_cons"
    build:
      context: ./bdd
      dockerfile: DockerfileSql
    environment:
      - MYSQL_ROOT_PASSWORD=pa

  serveur:
    container_name: "serveur_jar"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - bddmysql

  proxy:
    container_name: "proxy_serveur_jar"
    build:
      context: ./proxy
      dockerfile: DockerfileProxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - bddmysql
      - serveur

  angular:
    container_name: "front_angular"
    build:
      context: ./front-built
      dockerfile: DockerfileAngular 
    depends_on:
      - bddmysql
      - serveur
      - proxy
    ports: 
      - 4200:4200